// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPLuqv0Rou1pye0QqyGEcBK4QBUittAbo',
    appId: '1:939508688353:web:298bdf184da2e775a95ea0',
    messagingSenderId: '939508688353',
    projectId: 'bacaanku-app',
    authDomain: 'bacaanku-app.firebaseapp.com',
    storageBucket: 'bacaanku-app.firebasestorage.app',
    measurementId: 'G-7T476V1H9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3Ho4J29jiLdKTW-xdzJlo9b0mPDFhfCM',
    appId: '1:939508688353:android:2045c9e11210620ca95ea0',
    messagingSenderId: '939508688353',
    projectId: 'bacaanku-app',
    storageBucket: 'bacaanku-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcXEsoFMTFRWcgnGifDLWrrlqlpjVsOcc',
    appId: '1:939508688353:ios:020d62bc14be7673a95ea0',
    messagingSenderId: '939508688353',
    projectId: 'bacaanku-app',
    storageBucket: 'bacaanku-app.firebasestorage.app',
    iosBundleId: 'com.example.bacaanku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcXEsoFMTFRWcgnGifDLWrrlqlpjVsOcc',
    appId: '1:939508688353:ios:020d62bc14be7673a95ea0',
    messagingSenderId: '939508688353',
    projectId: 'bacaanku-app',
    storageBucket: 'bacaanku-app.firebasestorage.app',
    iosBundleId: 'com.example.bacaanku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPLuqv0Rou1pye0QqyGEcBK4QBUittAbo',
    appId: '1:939508688353:web:f79198f793a82c17a95ea0',
    messagingSenderId: '939508688353',
    projectId: 'bacaanku-app',
    authDomain: 'bacaanku-app.firebaseapp.com',
    storageBucket: 'bacaanku-app.firebasestorage.app',
    measurementId: 'G-0LS4K2CKDB',
  );
}
